// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvKE3MvBmolNtvfi_sK6I113hNEc8KbeM',
    appId: '1:48956061687:web:a56ac4267e43aaca2560f2',
    messagingSenderId: '48956061687',
    projectId: 'iventario-be57a',
    authDomain: 'iventario-be57a.firebaseapp.com',
    storageBucket: 'iventario-be57a.firebasestorage.app',
    measurementId: 'G-32PLZ9WJN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAargKTBCPJUXlKySi65f6xgZxNWKCjWq8',
    appId: '1:48956061687:android:8471fe3d7cc5e3eb2560f2',
    messagingSenderId: '48956061687',
    projectId: 'iventario-be57a',
    storageBucket: 'iventario-be57a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfKJ6XgSVaD4_PbFx1_5hvxUK5S5Zsno',
    appId: '1:48956061687:ios:16d44262c952e61f2560f2',
    messagingSenderId: '48956061687',
    projectId: 'iventario-be57a',
    storageBucket: 'iventario-be57a.firebasestorage.app',
    iosBundleId: 'com.example.gestionDeInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfKJ6XgSVaD4_PbFx1_5hvxUK5S5Zsno',
    appId: '1:48956061687:ios:16d44262c952e61f2560f2',
    messagingSenderId: '48956061687',
    projectId: 'iventario-be57a',
    storageBucket: 'iventario-be57a.firebasestorage.app',
    iosBundleId: 'com.example.gestionDeInventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvKE3MvBmolNtvfi_sK6I113hNEc8KbeM',
    appId: '1:48956061687:web:d080647d536e88482560f2',
    messagingSenderId: '48956061687',
    projectId: 'iventario-be57a',
    authDomain: 'iventario-be57a.firebaseapp.com',
    storageBucket: 'iventario-be57a.firebasestorage.app',
    measurementId: 'G-JXZNC2ZQZM',
  );
}
