// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPi2ffIv8gzOJ_O3I9ncMSdjZP_gcUTM',
    appId: '1:112416797159:ios:75688cecbccaa12fea4d42',
    messagingSenderId: '112416797159',
    projectId: 'inventario-app-2aa68',
    storageBucket: 'inventario-app-2aa68.firebasestorage.app',
    iosBundleId: 'com.example.gestionDeInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDPi2ffIv8gzOJ_O3I9ncMSdjZP_gcUTM',
    appId: '1:112416797159:ios:75688cecbccaa12fea4d42',
    messagingSenderId: '112416797159',
    projectId: 'inventario-app-2aa68',
    storageBucket: 'inventario-app-2aa68.firebasestorage.app',
    iosBundleId: 'com.example.gestionDeInventario',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwLMJyK0M0NKkiS-MH1is4F4RTYZqg1bA',
    appId: '1:112416797159:web:357e001f1dd98c92ea4d42',
    messagingSenderId: '112416797159',
    projectId: 'inventario-app-2aa68',
    authDomain: 'inventario-app-2aa68.firebaseapp.com',
    storageBucket: 'inventario-app-2aa68.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwLMJyK0M0NKkiS-MH1is4F4RTYZqg1bA',
    appId: '1:112416797159:web:357e001f1dd98c92ea4d42',
    messagingSenderId: '112416797159',
    projectId: 'inventario-app-2aa68',
    authDomain: 'inventario-app-2aa68.firebaseapp.com',
    storageBucket: 'inventario-app-2aa68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFPAZs5deTywn_eke2_eQHTKMlDeIhfSs',
    appId: '1:112416797159:android:520d96d1af9fe814ea4d42',
    messagingSenderId: '112416797159',
    projectId: 'inventario-app-2aa68',
    storageBucket: 'inventario-app-2aa68.firebasestorage.app',
  );

}